### ISSUE TITLE
Just a question regarding osslsigncode

### ISSUE THREAD

**Issue by exoosh** [mozilla-releng/winsign#40]
The README refers to [this dated version of osslsigncode](https://github.com/theuni/osslsigncode). Does Mozilla still use that or have you moved [to the existing active fork here](https://github.com/mtrojnar/osslsigncode/)? If you haven't moved to that, could you elaborate on the rationale, please?

I am also wondering if the `mtrojnar/osslsigncode` version of the code is compatible with your tooling or not. Any ideas?

Thank you.

Oliver

**Comment by jcristau** [comment]
We're currently using the osslsigncode package as shipped in Debian (via https://github.com/mozilla-releng/scriptworker-scripts/blob/master/signingscript/Dockerfile), which is indeed based on `mtrojnar/osslsigncode`.

**Comment by exoosh** [comment]
Thanks so much.
